### PR TITLE
Fix for: FixNum/Float/Boolean window names cause error

### PR DESCRIPTION
**Pull request by ncoop**
Refer to: https://github.com/tmuxinator/tmuxinator/issues/387

### CODE REVIEW

**Comment by ethagnawl** [comment]
[Rubocop is unhappy about the spacing in `match_array`](https://travis-ci.org/tmuxinator/tmuxinator/jobs/119365905#L1060-L1070). Otherwise, this looks good to me.

**Comment by ncoop** [comment]
OK, decided to squash the fix into that last commit.

**Comment by ethagnawl** [comment]
@adamstrickland @J3RN Any objections to me merging this PR?

**Comment by J3RN** [comment]
LGTM! :+1:

**Pull request merged**
