### PR TITLE
add tmux 2.9 support

### PR DESCRIPTION
**Pull request by teddyhwang**
tmuxinator works fine with tmux 2.9

### CODE REVIEW

**Comment by Croissong** [comment]
I ran into the same problem, thanks for the quick PR :)
On a side note: Is it possible to configure `tmuxinator start` to ignore the supported versions?
I'm running it in my xinit script and the "unsupported version" prompt caused it to crash silently.

**Comment by teddyhwang** [comment]
I think you can just add the `--suppress-tmux-version-warning` flag

**Comment by ethagnawl** [comment]
Thanks, @teddyhwang!

Would you mind adding an entry to CHANGELOG.md per [the contributing guidelines](https://github.com/tmuxinator/tmuxinator/blob/master/CONTRIBUTING.md#pull-requests)?

**Comment by teddyhwang** [comment]
@ethagnawl oof, my bad. Added!

**Pull request merged**
