### PR TITLE
Remove unnecessary code

### PR DESCRIPTION
**Pull request by evverx**
`project_file` always `nil`

### CODE REVIEW

**Comment by Soliah** [comment]
Looking at the code, `project_file` is only nil if you don't have any projects in `~/.tmuxinator`?

**Comment by evverx** [comment]
`project_file` nil because regexp in `project_file = projects.detect { |project| project =~ /^#{name}.yml$/ }` never matches.
You can reproduce:
```bash
vagrant-ubuntu-precise-32% mkdir -p ~/.tmuxinator
vagrant-ubuntu-precise-32% touch ~/.tmuxinator/{a,b,c,d,e}.yml
vagrant-ubuntu-precise-32% tree ~/.tmuxinator
/home/vagrant/.tmuxinator
├── a.yml
├── b.yml
├── c.yml
├── d.yml
└── e.yml

0 directories, 5 files
```

```ruby
vagrant-ubuntu-precise-32% pry
[1] pry(main)> require 'tmuxinator'
=> true
[2] pry(main)> name = 'a'
=> "a"
[3] pry(main)> projects = Dir.glob("#{Tmuxinator::Config.root}/**/*.yml")
=> ["/home/vagrant/.tmuxinator/e.yml",
 "/home/vagrant/.tmuxinator/c.yml",
 "/home/vagrant/.tmuxinator/a.yml",
 "/home/vagrant/.tmuxinator/b.yml",
 "/home/vagrant/.tmuxinator/d.yml"]
[4] pry(main)> project_file = projects.detect {|project| project =~ /^#{name}.yml$/}

=> nil
```

**Comment by Soliah** [comment]
Ah ok, that's because the `Dir.glob` returns the full path, so the `^` in the regex is incorrect.

**Comment by Soliah** [comment]
If you can remove the `^` in the regexp then I can merge this.

**Comment by evverx** [comment]
If I have `~/.tmuxinator/app1-dev.yml` and `name = 'dev'` , regex without `^` matches. It's incorrect.
Possible solution:
```ruby
projects = Dir.glob("#{root}/*.yml")
project_file = projects.detect { |project| File.basename(project, '.yml') == name }
```

**Pull request closed without merging**
