### PR TITLE
Synchronize panes support.

### PR DESCRIPTION
**Pull request by jessegonzalez**
I synchronize-panes all the time, and so may others.

### CODE REVIEW

**Comment by Loki-Afro** [comment]
+1!

**Comment by J3RN** [comment]
I'd like to see this feature merged. Though, since it's been a number of years it may take some time to coerce this into our codebase, since it's changed significantly over the intervening time. I'd be happy to help with that :smile:

**Comment by podung** [comment]
I'd love to see this feature get in as well.

**Comment by podung** [comment]
Thanks @jessegonzalez for your contributions.  @fabianschwarzfritz got this up to date and we got it committed.

**Pull request closed without merging**
