### PR TITLE
Issue 524 update ruby versions

### PR DESCRIPTION
**Pull request by adamstrickland**
Suggested changes for #524

### CODE REVIEW

**Comment by adamstrickland** [comment]
Does anyone mind if I merge this in to master?  This (i.e. updating our supported rubies) should be done regularly.  The question is, do we want to (continue to) support versions of ruby for tmuxinator that are no longer themselves supported?

**Comment by J3RN** [comment]
@adamstrickland FWIW: Yes, I think we should merge this :+1: and should do so regularly. No, I don't think we should support rubies that the ruby maintainers have decided to no longer support. I hope, for security reasons, mostly, that no one is using an unsupported ruby. Besides, one can install a supported ruby and tmuxinator with it while using an unsupported ruby for work, etc.

**Comment by ethagnawl** [comment]
@adamstrickland Supporting only modern Rubies sounds reasonable to me. 

Out of curiosity, how do we determine which patch version to support/test against? Should it always be the most recent stable release? FWIW, the three versions specified in .travis.yml and tmuxinator.gemspec are all one patch behind the most recent stable versions.

**Comment by adamstrickland** [comment]
@ethagnawl I chose the 3 most-recent stable versions at the time I submitted the PR.  As you noted, that has since changed; I have bumped the versions accordingly.

In general, I think we should simply try to stay current, bumping to the most recent stable on a regular basis, but IMO we don't need to watch it like a hawk, either.

**Pull request merged**
