### PR TITLE
Load compinit before compdef

### PR DESCRIPTION
**Pull request by HaleTom**
Fix command not found: compdef #705

### CODE REVIEW

**Comment by ethagnawl** [comment]
This looks good to me, but I don't use zsh.

Does anyone @tmuxinator/tmuxinator who's familiar with zsh mind having a look?

**Comment by rglassett** [comment]
I'm only a casual zsh user, so take with a grain of salt; but as far as I can tell this isn't the conventional way to define completion functions. `compinit` is meant to be called from the user's `~/.zshrc`, and the definitions are loaded from files in the `$fpath` variable. [Git completion](https://github.com/git/git/blob/master/contrib/completion/git-completion.zsh) looks to be a good example.

I'll need to read up on it more, but I think the actual completion file should look something like this:

```
# tmuxinator/completion/tmuxinator.zsh

_tmuxinator() {
  # logic
}

_tmuxinator
```

To install, users would copy the file to `$ZDOTDIR/functions/Completion/_tmuxinator` and add to their `~/.zshrc`:

```
fpath=($ZDOTDIR/functions/Completion $fpath)
autoload -Uz compinit
compinit

# optional alias
alias mux="tmuxinator"
compdef mux=tmuxinator
```

I'll try to find time over the weekend to read up and do a refactor.

**Comment by Rahlir** [comment]
I believe this is the correct approach:
https://github.com/zsh-users/zsh-completions/blob/master/src/_tmuxinator

**Comment by Rahlir** [comment]
Note that for such completions, the file should be placed in a directory (typically used for zsh completions in general) that is present in your `$fpath`

**Comment by ethagnawl** [comment]
@HaleTom @rglassett What is everyone thinking about the existing vs. proposed solutions?

**Comment by doronbehar** [comment]
@ethagnawl @Rahlir is correct, I was about to file an issue / PR about this as well: In short, ZSH completions aren't files you source in your `~/.zshrc`. You are supposed to put them in your `$fpath` and they'll be loaded on demand. The better PR should be this:

```patch
diff --git c/completion/tmuxinator.zsh i/completion/tmuxinator.zsh
index e77f1ed..e291eac 100644
--- c/completion/tmuxinator.zsh
+++ i/completion/tmuxinator.zsh
@@ -1,3 +1,4 @@
+#compdef _tmuxinator tmuxinator
 _tmuxinator() {
   local commands projects
   commands=(${(f)"$(tmuxinator commands zsh)"})
@@ -18,8 +19,6 @@ _tmuxinator() {
   return
 }
 
-compdef _tmuxinator tmuxinator mux
-alias mux="tmuxinator"
 
 # Local Variables:
 # mode: Shell-Script
```

Along with a README update as well.

**Comment by doronbehar** [comment]
BTW AFAIK fish and bash are the same - you don't need to source anything, just put it in a location the shell looks for completions in it. Usually that's taken care of by the package.

**Comment by ethagnawl** [comment]
Thanks for this, @doronbehar.

> The better PR should be this:

Does anyone have thoughts on this? It'd be nice to get this sorted out and ship it in the next release.

**Comment by ethagnawl** [comment]
@doronbehar @HaleTom @rglassett Any thoughts on the above? I'm hoping to cut a release today or tomorrow and it'd be nice to get this in for the zsh folks.

**Comment by doronbehar** [comment]
I've stated my opinion in my previous reply - https://github.com/tmuxinator/tmuxinator/pull/706#issuecomment-546596771

**Comment by patrick96** [comment]
I didn't even know tmuxinator had its own zsh completion, I always used the `zsh-completions` package.

But @doronbehar's changes look good to me and the zsh-completions project's [guide](https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org#telling-zsh-which-function-to-use-for-completing-a-command) seems to agree.

But the completions file should be named `_tmuxinator` and the README needs to be adjusted to tell the user to put it into a directory in the `fpath`.

**Comment by ethagnawl** [comment]
Please feel free to update this PR or submit a new one.

**Pull request closed without merging**
