### PR TITLE
Update stop command to support project-config and omitting project name

### LINKED ISSUE #626: "tmuxinator stop" without arguments
You can `tmuxinator start` in a directory, but you aren't able to `tmuxinator stop` without adding something so it doesn't complain about missing arguments.

Is it possible to remove this requirement?

### PR DESCRIPTION
**Pull request by ToranSharma**
Brings stop command in line with start command.

Can now stop a project started with the `--project-config` flag by running a stop command with the same flag. For instance the example in the README.md can now be stopped:
```
tmuxinator start --project-config=path/to/my-project.yaml
tmuxinator stop --project-config=path/to/my-project.yaml
```

Stopping the default local project (`./.tmuxinator.yml`) is now easier and matches the short way or starting it:
`tmuxinator start` to start, `tmuxinator stop` to stop. I think this then closes #626.

---

My use case is having multiple local `.yml` project config files which have different `on_project_start` tasks that need to be cleaned up with a corresponding `on_project_stop`. Currently there is no way to get the `on_project_stop` hook to run if you started the project using the `--project-config` flag.

### CODE REVIEW

**Review by akofink — APPROVED** [review]
Works as expected. Nice one! 🥇 

I tested it with a project config and with omitting all arguments:

```
$ bundle exec tmuxinator start -p spec/fixtures/nameless_window.yml
[detached (from session nameless_window)]

$ tmux list-sessions
nameless_window: 2 windows (created Tue Jan 30 18:45:43 2024)

$ bundle exec tmuxinator stop -p spec/fixtures/nameless_window.yml

$ tmux list-sessions
no server running on /private/tmp/tmux-501/default

$ bundle exec tmuxinator stop
Project file at ./.tmuxinator.yml doesn't exist.
```

The tests match those for the start command as well and appear to cover all scenarios.

**Comment by akofink** [comment]
Anyone else from @tmuxinator/tmuxinator want to weigh in on this one?
It looks ready to merge with good test coverage and CHANGELOG additions 🎉

**Review by adamstrickland — APPROVED** [review]

**Comment by akofink** [comment]
Thanks again, @ToranSharma! 🙌

**Comment by ToranSharma** [comment]
Cheers @akofink @adamstrickland

**Pull request merged**
