### PR TITLE
Config.root refactoring

### PR DESCRIPTION
**Pull request by ethagnawl**
There were a few issues that led me to making this change:

1. there were two different string representations of the path `~/.tmuxinator` in use (`"#{ENV['HOME']}/.tmuxinator"` and `"~/.tmuxinator"`)
2. the path is available as the return value of the call to `File.expand_path`, so it'd seem to reason that only one string representation should be necessary

I looked through the history, but didn't see any reference to needing to use the different representations to support various environments/platforms. Please chime in if anyone has any insight as to why those different variations were used and/or if one should be used instead of the other in the call to `File.expand_path`.

### CODE REVIEW

**Comment by J3RN** [comment]
I, for one, 👍 this. Also another 👍 for updating `CHANGELOG.md`!

**Comment by ethagnawl** [comment]
Fixed merge conflict in CHANGELOG.md.

**Comment by J3RN** [comment]
@ethagnawl Are we ready to merge this one?

**Comment by adamstrickland** [comment]
:shipit:

**Comment by ethagnawl** [comment]
@J3RN If people are content with using `"#{ENV['HOME']}/.tmuxinator"` instead of `"~/.tmuxinator"` (the former is used elsewhere in config.rb), I think we should merge this one.

**Comment by J3RN** [comment]
I'd say that sounds like a pretty safe bet!

**Pull request merged**
