### PR TITLE
A more precise pre/post deprecation warning

### PR DESCRIPTION
**Pull request by jumph4x**
Just a little something to let users get rid of the deprecation warning, especially those of us who haven't been keeping up with the project.

### CODE REVIEW

**Comment by ethagnawl** [comment]
Hey @jumph4x,

Thanks for this!

Two pieces of feedback:
- Should "on_start" read "on_project_start"?
- Should "on_detach" read "on_project_exit" and/or "on_project_stop"?

**Comment by jumph4x** [comment]
I don't know, I tried to read the source to figure it out.

Changing it to 'on_start' didn't work, so you're probably right. Will fix.

**Comment by ethagnawl** [comment]
@jumph4x Any chance you'd be willing to revisit this?

I see two trivial issues which need to be addressed:
- Fix the merge conflict. (All of the messages now use sentence formatting and backticks where appropriate.)
- Use the latest hooks (as mentioned above)

**Comment by ethagnawl** [comment]
Supplanted by #670.

**Pull request closed without merging**
