### PR TITLE
Add option "tmux_detached" for detach client

### PR DESCRIPTION
**Pull request by mvaraga**
This option specifies if tmux start with attached or detached state.
Start attached when "false" or option not defined, otherwise detached.
As requested in #191 #224

### CODE REVIEW

**Comment by maxmeyer** [comment]
@Soliah 
Does it make sense to add a "detached"-option to `start` as well?

```bash
tmuxinator start <project> --detached
```

This way one could add it to a shell initscript.
```
tmuxinator start project_1 --detached
tmuxinator start project_2 --detached
tmuxinator start project_3 --detached
tmuxinator start project_4 --detached
```

Would love to see this merged.

**Comment by Soliah** [comment]
Command line flag would be great. Thor makes it relatively easy to add the option if you want to have a go @mvaraga?

**Comment by mvaraga** [comment]
I do it. Should I preserve option in project file and override it with start option. Or just start option?

**Comment by maxmeyer** [comment]
Personally I would expect that the --detach-option will override the configuration in the project config-file.

**Comment by Soliah** [comment]
Yes sounds good that the command line option takes precedence.

**Comment by paularmstrong** [comment]
This is great! Definitely a helpful addition.

**Comment by maxmeyer** [comment]
@mvaraga Any progress on that? ;-) Any help needed?

**Comment by Soliah** [comment]
Thinks #293 deals with this now. Can you please try and comment in that issue for followup.

**Pull request closed without merging**
