### PR TITLE
Fix spacing in command list and add edit command to command list

### LINKED ISSUE #415: Command descriptions not aligned correctly with mux help or autocomplete
When using autocomplete or `mux help`, the info about the `start`, `stop`, and `copy` commands has a tab between the `#` and the info causing their info to not line up with the rest of the commands. Also, no edit command is listed.

### PR DESCRIPTION
**Pull request by cwhits**
There was a tab for the start, stop, and copy commands that would cause `mux help` and autocomplete to have the command descriptions not line up properly. 

Also, since there was no `edit` command displayed, it wouldn't appear when using autocomplete.

Closes #415.

### CODE REVIEW

**Comment by ethagnawl** [comment]
Thanks for putting this together, @cwhits.

Presumably, those heredocs were used to keep the lines from extending past 80 columns. If people feel strongly about keeping lines below 80 columns (I don't see mention of this anywhere in README, CONTRIBUTING, rubocop.yml, etc.), we could consider doing something like [this](https://gist.github.com/ethagnawl/680d6195b30247291fddea3ca6514da7) to strip any leading spaces.

**Comment by cwhits** [comment]
Getting rid of the tab at the beginning of the line would probably also fix it, but it'd look weird with those sections not being aligned.

```ruby
        stop: <<-DESC,
Stop a tmux session using a project's tmuxinator config.		
        DESC		
```

**Comment by cwhits** [comment]
Aw, I forgot to update the changelog :( 

Sorry.

**Comment by cwhits** [comment]
It also appears to mess up the autocomplete with zsh, cutting the heredoc lines and putting them at the bottom of the command list for some reason.

```
~/g/tmuxinator (help_update) $ tmuxinator help
tmuxinator commands:
  tmuxinator commands                          # Lists commands available in tmuxinator
  tmuxinator completions [arg1 arg2]           # Used for shell completion
  tmuxinator copy [EXISTING] [NEW]             #  Copy an existing project to a new project and open it in your editor 
  tmuxinator debug [PROJECT] [ARGS]            # Output the shell commands that are generated by tmuxinator
  tmuxinator delete [PROJECT1] [PROJECT2] ...  # Deletes given project
  tmuxinator doctor                            # Look for problems in your configuration
  tmuxinator help [COMMAND]                    # Describe available commands or one specific command
  tmuxinator implode                           # Deletes all tmuxinator projects
  tmuxinator list                              # Lists all tmuxinator projects
  tmuxinator local                             # Start a tmux session using ./.tmuxinator.yml
  tmuxinator new [PROJECT]                     # Create a new project file and open it in your editor
  tmuxinator start [PROJECT] [ARGS]            #  Start a tmux session using a project's tmuxinator config, with an optional [ALIAS] for project reuse 
  tmuxinator stop [PROJECT]                    #  Stop a tmux session using a project's tmuxinator config. 
  tmuxinator version                           # Display installed tmuxinator version

~/g/tmuxinator (help_update) $ tmuxinator
 -- tmuxinator subcommands --
commands                                            -- Lists commands available in tmuxinator
completions                                         -- Used for shell completion
copy                                                --         Copy an existing project to a new project and open it in
debug                                               -- Output the shell commands that are generated by tmuxinator
delete                                              -- Deletes given project
doctor                                              -- Look for problems in your configuration
implode                                             -- Deletes all tmuxinator projects
list                                                -- Lists all tmuxinator projects
local                                               -- Start a tmux session using ./.tmuxinator.yml
new                                                 -- Create a new project file and open it in your editor
open                                                -- Alias of new
start                                               --         Start a tmux session using a project's tmuxinator config,
stop                                                --         Stop a tmux session using a project's tmuxinator config.
version                                             -- Display installed tmuxinator version
        with an optional [ALIAS] for project reuse          your editor                               
 -- tmuxinator projects --
Work                              Play                              Test                            
```

**Comment by ethagnawl** [comment]
Another alternative would be to use an array instead of a heredoc. It's not particularly pretty, but it solves the problem and avoids the weird edge-cases presented by heredocs.
 
      ...
      start: %w{
      Start a tmux session using a project's tmuxinator config,
      with an optional [ALIAS] for project reuse
      }.join(' ')
      ...
```

λ ./bin/tmuxinator help start
Usage:
  tmuxinator start [PROJECT] [ARGS]

Options:
  -a, [--attach], [--no-attach]  # Attach to tmux session after creation.
  -n, [--name=NAME]              # Give the session a different name

Start a tmux session using a project's tmuxinator config, with an optional [ALIAS] for project reuse

```

**Comment by cwhits** [comment]
@ethagnawl: Want me to update the PR to use arrays?

**Comment by ethagnawl** [comment]
@cwhits I'm not opposed to that. Does anyone else (@J3RN, @adamstrickland) want to chime in?

**Comment by J3RN** [comment]
I'm all in favor of arrays. It looks like the heredoc style is used in `lib/tmuxinator/project.rb` and `spec/lib/tmuxinator/project_spec.rb`, however, but I'm willing to allow this inconsistency.

**Comment by ethagnawl** [comment]
Great. 

It may be worth opening a separate issue to address those instances. I haven't had a chance to test those messages in a terminal, but it looks like they're probably plagued by this issue, too.

**Comment by adamstrickland** [comment]
+1

**Comment by ethagnawl** [comment]
Hey @cwhits, any update on this PR? I'm happy to take over if you've moved on. :)

**Comment by cwhits** [comment]
@ethagnawl: I updated it but only changed the lines that were over 80 cols. This is the first time I've ever touched ruby so I don't actually know how to build the binary to test it.

**Comment by ethagnawl** [comment]
@cwhits You should be able to run `./bin/tmuxinator help` from the repository's root directory.

**Comment by cwhits** [comment]
Using arrays fixed the spacing issues. The only thing I noticed is that the "aliases of new" (`edit` and `open`) don't appear in the help menu. They do appear when running `tmuxinator commands` and function correctly when running `tmuxinator completions _____`.

I'm not entirely sure how to make them appear when running `tmuxinator help` without explicitly defining them. E.g.,
```ruby
    desc "edit [PROJECT]", COMMANDS[:edit]
    def edit(name)
        invoke :new, name
    end
```

**Comment by ethagnawl** [comment]
> The only thing I noticed is that the "aliases of new" (edit and open) don't appear in the help menu. They do appear when running tmuxinator commands and function correctly when running tmuxinator completions _____.

@cwhits That's very perceptive. Though, it seems like this was a deliberate choice by the Thor folks. `aliases`/`map` appear meant for use in specifying _abbreviations_, as opposed to _aliases_ (despite the metadata option name). Quoting [whatisthor.com](http://whatisthor.com/), "Typically, you would use aliases to provide short versions of the option." e.g. `map "n" => :new`

I think we should create a new issue in order to determine 1) whether this is worth addressing and 2) what potential solutions could look like.

**Comment by ethagnawl** [comment]
@cwhits Looks like the only outstanding issues are the Rubocop violations: using two spaces to indent the array members and replacing the single-quotes with double-quotes in the call to `.join`. 

Apologies for using non-conforming formatting in my initial suggestion.

**Comment by cwhits** [comment]
No problem, I'll get those fixed up.

**Comment by ethagnawl** [comment]
@podung @J3RN @adamstrickland Any opposition to merging this PR?

**Comment by J3RN** [comment]
I haven't tested it, but I'm sure it's good. I'm in favor! :+1:

**Comment by adamstrickland** [comment]
👍

**Comment by ethagnawl** [comment]
@cwhits Would you mind updating CHANGELOG.md, so we can get this merged?

**Comment by podung** [comment]
👍

**Comment by ethagnawl** [comment]
@cwhits Thanks! Unfortunately, there's now a merge conflict in CHANGELOG.md. :crying_cat_face:

**Comment by cwhits** [comment]
shoot, I forgot to pull in any changes before updating it.

**Comment by ethagnawl** [comment]
@podung @J3RN @adamstrickland This build is failing because Travis is unable to install ActiveSupport 5.0 (I _believe_ this is being caused by FactoryGirl). Should we merge this PR (the tests pass and the build _was_ passing) and sort out that issue elsewhere or attempt to handle that in this PR? 

If it's the latter, I don't know what the appropriate fix is (declare a dependency on ActiveSupport 4.2.6 in the Tmuxinator Gemfile?), so please feel free to propose suggestions.

**Comment by adamstrickland** [comment]
@cwhits when you have a chance, would you pull the latest origin/master into your branch?  @ethagnawl  repaired the cause of the failed build and I just merged it in.  Should just be able to pull and push.  Once we are green, we'll merge ASAP.

**Comment by cwhits** [comment]
@adamstrickland sure thing.

**Comment by ethagnawl** [comment]
Thanks, @cwhits!

Now that that is all settled. Is anyone opposed to me merging this?

**Comment by adamstrickland** [comment]
yes, thanks @cwhits!

👍 LGTM

**Pull request merged**
