### PR TITLE
Add support list --newline (#678)

### PR DESCRIPTION
**Pull request by raiyuza**
Add support list --newline (#678)

created a --newline flag for the ``list`` command. Read up on issue #678 [here](https://github.com/tmuxinator/tmuxinator/issues/678)
```bash
-n, [--newline], [--no-newline]  # Force output to be one entry per line
```

Small sidenote:
this is my first public MRQ and ruby contribution, any feedback is welcome

### CODE REVIEW

**Comment by raiyuza** [comment]
Uploaded wrong code while trying to squash rookie mistake, hold on!

**Comment by raiyuza** [comment]
1. I will in a few minutes! 

> 2. Maybe the newline option should become the default? Though, I guess this could potentially break other people's workflows in the opposite direction and could warrant a deprecation warning for a release cycle or two..

Hmmm,

We can keep the default behavior by giving it a seperator flag ala awk -F though. Users can set an env variable to control the default value of this flag. This way you don't have to break backwards compatibility and it makes the feature more useful overall.

In the same fashion it would be amazing to have have some kind of --format option, it would be able te
format how the list command would show your list, and extract properties from said projects. Ex.

```
$> mux l -F "\n" --format "@name\t@root\t@windows.editor.layout"
$> 
foo<tab>~/foo<tab>vertical
bar<tab>~/bar<tab>horizontal
```

This opens up an powerful way to create a formatted data structure. This mainly used for parsers in Ex.

 - vim, you could write a unite/denite script to read the outputs buffer to make menu's 
 - fuzzy search

Ill create an issue with this idea, better to discuss it there.

Thanks for the feedback!

**Comment by ethagnawl** [comment]
Thoughts, @tmuxinator/tmuxinator?

**Comment by rglassett** [comment]
Neat feature. Ideally I'd like to see a test assertion against the actual output format, but most of the other CLI tests don't really do this either, so the new test meets the current bar IMO.

:+1: from me.

**Comment by raiyuza** [comment]
I created a new issue with the new idea [here](https://github.com/tmuxinator/tmuxinator/issues/681) .

Let's keep the scope of this issue/PRQ to the -n flag only. Makes it easier to segment what we are talking about!

**Pull request merged**
