### PR TITLE
introduce Contributor Covenant

### PR DESCRIPTION
**Pull request by ethagnawl**
There'd been talk about this issue in the Gitter channel, but I wanted to get the ball rolling.

The only piece of this to figure out is how to handle communication. Who should reports be sent to? Me? Willing core contributors? A private mailing list?

### CODE REVIEW

**Comment by J3RN** [comment]
I'm glad to see you opened this! Like I said in the Gitter channel, I am fully in support of adding this. Since the build failed for some issue with `sudo apt-get...`, I restarted it. It should be fine, I imagine.

I would be fine with taking reports, but I'd probably set up a separate email account for just that. A private mailing list also sounds like a great idea, but I'm unsure how to get one set up.

**Comment by ethagnawl** [comment]
> I would be fine with taking reports, but I'd probably set up a separate email account for just that.

OK - that seems like the simplest way forward. In the unlikely scenario that you find yourself swamped by reports, we could investigate setting up an invite-only Google Group or something.

**Comment by J3RN** [comment]
Yeah, you're right - It's unlikely that my email will get swamped with reports, so there's probably no need to go through the hassle of setting up another email account. Would you like me to open a PR against this one containing my email?

**Comment by ethagnawl** [comment]
Would you like me to drop-in the email address in your profile?

**Comment by J3RN** [comment]
@ethagnawl That works for me!

**Comment by J3RN** [comment]
:+1:

**Comment by Soliah** [comment]
Hey guys who should I make an owner on the project? Clearly I'm not really doing much with it anymore so should really give ownership to the repo to someone else too.

**Comment by J3RN** [comment]
@Soliah Naturally, I'd be honored to be an (the?) owner of the repo. That said, I'm a relatively newer contributor, so I can understand you objecting to giving me ownership.

**Comment by ethagnawl** [comment]
Shall I merge this?

**Comment by adamstrickland** [comment]
LGTM :+1:

**Pull request merged**
