### PR TITLE
Resolve window root relative to project root

### LINKED ISSUE #410: Resolve window/root relative to project root
If you have multiple windows with differing roots (#283), you have to specify an absolute path for all windows. This can lead to your .conf looking like:

```
name: example
root: ~/Work/Projects/Example

windows:
  - vagrant:
      root: ~/Work/Projects/Example
      panes:
        - vagrant status
  - frontend:
      root: ~/Work/Projects/Example/frontend
      panes:
        -
  - frontend-build:
      root: ~/Work/Projects/Example/frontend
      panes:
        - grunt
  - app:
      root: ~/Work/Projects/Example/app
      panes:
        -
```

This involves a bunch of path duplication. Unfortunately, relative paths are resolved relative to the working dir of tmuxinator, which makes usage unreliable. Instead, it'd be great to have this resolve relative to the project root instead.

### PR DESCRIPTION
**Pull request by rmccue**
Fixes #410.

### CODE REVIEW

**Comment by adamstrickland** [comment]
Can you add a test for this in keeping with the contribution guidelines, please?

**Comment by J3RN** [comment]
Also a note in the `CHANGELOG.md` file under a new title of "## Unreleased"? Sorry, that should be in there but this is the first new change since our last release.

**Comment by rmccue** [comment]
Not a Rubyist, just a fan of tmuxinator, so might take me a little while to get that sorted, but I'll give it a shot :)

**Comment by ethagnawl** [comment]
While I do like that your change is explicit about what's being passed to `File.expand_path`, it may be worth considering that `Project#root` [contains an identical ternary](https://github.com/tmuxinator/tmuxinator/blob/master/lib/tmuxinator/project.rb#L94). As such, we could abide by the [TellDontAsk](http://martinfowler.com/bliki/TellDontAsk.html) principle and always pass its return value through to `File.expand_path`:

`File.expand_path(value["root"], project.root).shellescape`

I don't feel too strongly about this either way, I just thought I'd propose the change while this PR is still in-flight. :)

**Comment by ethagnawl** [comment]
@rmccue Is there any chance you'll be able to revisit this PR? If not, I'd be happy to take over.

**Comment by adamstrickland** [comment]
@ethagnawl it looks like @rmccue is not able to revisit this.  Do you want to take it on?

Closing due to inactivity.

**Comment by ethagnawl** [comment]
@adamstrickland Sure, I can revisit this.

**Pull request closed without merging**
