### PR TITLE
add zshell completions for command aliases

### PR DESCRIPTION
**Pull request by remyoudemans**
Up until now, in zsh you had to type out the full command
(like "tmuxinator start") for tab completions to work.
This makes it work for aliases too (like "tmuxinator s").

### CODE REVIEW

**Comment by ethagnawl** [comment]
Would anyone who uses zsh mind reviewing this? @tmuxinator/tmuxinator

**Comment by magicalbanana** [comment]
@remyoudemans can you elaborate? Do you mean, when you did `tmuxinator ...` it didn't display the autocompletions?

**Comment by remyoudemans** [comment]
@magicalbanana no. I made the project completions work for command aliases.
What already existed was that if I typed `tmuxinator start ` and then pressed tab, it would complete to one of my projects like `tmuxinator start myProject`.

However, if I used the alias for `start` which is `s` and then pressed tab (`tmuxinator s ` and then tab), I would get no completions.

All I did was make it check for completions not only when a full command is written (`start`, `edit` ...) but also when you use aliases (`s`, `e` .....)

**Comment by magicalbanana** [comment]
@remyoudemans gotcha. Thank you for the clarification. This looks good to me.

**Pull request merged**
