### PR TITLE
Commenting out Shorthand section of README until mux symlink issue has been addressed

### PR DESCRIPTION
**Pull request by ethagnawl**
This should help prevent any new "mux doesn't work" bug reports.

### CODE REVIEW

**Comment by ethagnawl** [comment]
If this is merged, we'll likely want to make a note of it in #401.

**Comment by J3RN** [comment]
:+1: I fully support this. Making a note on #401 of a new idea I had in relation to this.

**Comment by adamstrickland** [comment]
👍

**Comment by ethagnawl** [comment]
Does anyone have additional thoughts on this PR or shall we merge it?

**Comment by J3RN** [comment]
I am all in favor of this being merged.

**Pull request merged**
