### PR TITLE
Minor correction in README

### PR DESCRIPTION
**Pull request by KevinSjoberg**

### CODE REVIEW

**Comment by adamstrickland** [comment]
Any ideas on why the build is failing on 1.9.3?

**Comment by KevinSjoberg** [comment]
@adamstrickland hmm, interesting. It should not be something related to this pull request at least. I just ran `bundle install --jobs=3 --retry=3` on my machine for the `master` branch of tmuxinator using Ruby version `ruby 1.9.3p551` and it ran just fine.

**Comment by adamstrickland** [comment]
I agree, I did the same and likewise had no problem (not to mention the fact that this change is immaterial to the gem's install...).

    _____________________________

**Comment by adamstrickland** [comment]
So, when I set up my dev environment to mirror the `ruby`/`gem`/`bundler` setup that's indicated in the travis build log, I was able to reproduce the error.  It looks like this is due to a bug in bundler 1.7.6, which is the default bundler version used by travis (see https://github.com/travis-ci/travis-ci/issues/5239).  On my local, when I updated to the most recent version of bundler (1.11.2), everything seems good.

I'm going to recommend we change the travis setup to use a more recent version than 1.7.6 (see https://github.com/travis-ci/travis-ci/issues/3531) as many other FOSS projects are doing.

I have pushed a [PR](https://github.com/tmuxinator/tmuxinator/pull/365) to address this.  We'll merge it in and then let's see if that solves the error in this branch.

**Comment by adamstrickland** [comment]
@KevinSjoberg would you pull upstream master into your branch so we can see if that takes care of the travis failures?

**Comment by ethagnawl** [comment]
@KevinSjoberg The build is still failing, so I wanted to bump @adamstrickland's request to merge upstream/master into your PR. I'd be happy to open a new PR if you're unable to follow-up on this one.

**Comment by KevinSjoberg** [comment]
@ethagnawl I'll rebase with upstream/master as soon as I get home. Sorry for the delay. Totally blanked out on this one.

**Comment by ethagnawl** [comment]
@KevinSjoberg Great. Thanks!

**Comment by KevinSjoberg** [comment]
@adamstrickland @ethagnawl I've rebased with `upstream/master` and Travis seems happy as well! :smile:

**Comment by ethagnawl** [comment]
Thanks for following-up, @KevinSjoberg!

**Pull request merged**
