### PR TITLE
Bump license years for 2017

### PR DESCRIPTION
**Pull request by sachin21**
Happy New Year!

### CODE REVIEW

**Comment by ethagnawl** [comment]
@sachin21 It's probably overkill, but would you mind adding a note to CHANGELOG.md?

**Comment by J3RN** [comment]
@ethagnawl Since this is a really minor change and there's some delay with getting the CHANGELOG updated, would you be alright with merging this anyways?

**Comment by ethagnawl** [comment]
@J3RN Sure, that works for me.

**Comment by sachin21** [comment]
I'm sorry for the late. I also think this is a really minor change. Many repositories does not write CHANGELOG.md.

**Pull request merged**
