### PR TITLE
Add Stop Command

### PR DESCRIPTION
**Pull request by dannluciano**
Add Stop Command aka `tmux kill-session -t project`

### CODE REVIEW

**Comment by adamstrickland** [comment]
Tests need to pass, of course :)

@ethagnawl :+1:

**Comment by dannluciano** [comment]
@ethagnawl How we do the stop command without project name?
The commands are closely linked to the project module.

**Comment by ethagnawl** [comment]
@dannluciano You're right, it's not as straightforward as I would have hoped. I'll take a pass at it in a separate PR.

**Comment by dannluciano** [comment]
@ethagnawl what the problem with Travis? Can you restart the job https://travis-ci.org/tmuxinator/tmuxinator/jobs/114553630 ?

**Comment by ethagnawl** [comment]
@dannluciano I'm not sure what the issue was, but I just restarted the job.

**Comment by dannluciano** [comment]
Nice, now all tests are fine. ^^.

**Comment by ethagnawl** [comment]
@adamstrickland Shall we merge this?

**Comment by adamstrickland** [comment]
Merged

**Pull request merged**
