### PR TITLE
Simple maintenance improvements

### PR DESCRIPTION
**Pull request by a1346054**
Review comments are very welcome.

### CODE REVIEW

**Comment by a1346054** [comment]
I can remove the alias-removing commit and create a new PR for it to discuss it there, are you ok with that?

The unnecessary shebang causes warnings in tools like lintian https://lintian.debian.org/tags/bash-completion-with-hashbang . A comment at the top that doesn't start with `#!` is perfectly fine to help guide text editors. I've also seen them have it as a comment at the very end of file (at least vim supports that). There are plenty of other alternatives with varying levels of support, such as having hints in .gitattributes, but ultimately it's up to the user to modify their own environment to understand what the file contains. The completion script is edited so very rarely that I don't see it as a big problem if the user has to type `:set ft=sh` or similar.

**Comment by ethagnawl** [comment]
@a1346054 That all sounds good by me. Thanks again.

**Comment by a1346054** [comment]
I removed the commit that removes the `mux` alias as requested, rebased on latest master to fix merge conflicts, and added a few fixes for typos.

**Comment by ethagnawl** [comment]
Thanks, @a1346054! Would you mind adding an entry to the changelog for these changes? After that, I'll merge this PR.

**Review by akofink — APPROVED** [review]

**Pull request merged**
