### PR TITLE
#390 - fix local project deletion

### PR DESCRIPTION
**Pull request by ethagnawl**
Addresses #390.

### CODE REVIEW

**Comment by ethagnawl** [comment]
I just noticed the RuboCop failure. I'm on my way out of town for the next week, so unless someone else wants to jump in and replace the single-quotes, this one will have to wait a bit.

We might want to roll RuboCop, Rspec, et al into a

**Comment by ethagnawl** [comment]
I'm going to be away from my computer for the next week, so if someone wants to fix the RuboCop error, I'd be greatful. Otherwise, this will need to sit on the backburner for a bit.

Relatedly, we might want to consider rolling RuboCop, Rspec, et al into a common "test" Rake task. I regularly forget to run RuboCop and based on build errors in other PRs I've seen, I suspect others do too.

**Comment by J3RN** [comment]
@ethagnawl I'd be happy to do the single quote fix, but unfortunately since it's on your fork, I probably don't have push access. That's alright though, I don't think we're in any enormous hurry. Enjoy your time off! :palm_tree:

You're right about doing `rake test`. I created #398

**Comment by ethagnawl** [comment]
@J3RN OK - I've (finally!) resolved the RuboCop issue.

**Comment by J3RN** [comment]
@ethagnawl Alright, looks good! Does this branch have the updated CHANGELOG? If so, would you mind throwing a note about this change in there?

**Comment by ethagnawl** [comment]
@J3RN Rebased and updated CHANGELOG.md.

**Comment by J3RN** [comment]
@ethagnawl Alright, this looks good to merge!

**Pull request merged**
