### PR TITLE
Allow YAML aliases to work

### PR DESCRIPTION
**Pull request by agios**
This functionality needs to be explicitly enabled with safe_load

### CODE REVIEW

**Comment by agios** [comment]
Also added a test.

@tmuxinator/tmuxinator has anyone had a chance to look at this? YAML aliases allow one to have global configuration default template snippets.

**Comment by ethagnawl** [comment]
Thanks for this, @agios. I will try to review it today.

**Comment by ethagnawl** [comment]
@agios I just experimented with this locally and it works well. This will make for a nice addition to tmuxinator!

Would you mind adding an entry to CHANGELOG.md using the instructions in CONTRIBUTING.md?

**Comment by agios** [comment]
Added changelog note. This used to work already before, it was inadvertently broken by https://github.com/tmuxinator/tmuxinator/commit/2cd3c675feaf02967633b986f16e6be8b928b003.

Perhaps what might be more interesting is a use case for this. Eg, you can use a defaults file, with the structure for various types of projects (rails, rails+docker, etc) and in an actual project file just write:

```yaml
name: test
root: ~/test

<%= Erubis::Eruby.new(File.read("#{ENV['HOME']}/.tmuxinator/defaults")).evaluate(self) %>

<<: *rails-docker-defaults
```

**Pull request merged**
