### PR TITLE
Configure Bundler cache in Travis config

### PR DESCRIPTION
**Pull request by ethagnawl**

### CODE REVIEW

**Comment by ethagnawl** [comment]
This addition doesn't improve CI build times.

**Comment by Taher-Ghaleb** [comment]
> This addition doesn't improve CI build times.

I see your point, @ethagnawl. 

Any reasons why bundler caching wasn't used in the past? I am doing research and would appreciate any justifications. Thanks.

**Comment by ethagnawl** [comment]
I couldn't say. I didn't setup the Travis integration.

**Comment by Taher-Ghaleb** [comment]
I see. Thank you for your quick response.

**Pull request closed without merging**
